
from construct import *
from eagle_adapters import *
from utils import HexLineAdapter
from utils import to_bin

UNKNOWN = Struct("UNKNOWN",
    HexLineAdapter(Field("data", 22)),
)

ROTATION = Embed(RotationAdapter(
    BitStruct("rot_flags",
        BitField("rot_low", 8),
        Padding(1),
        BitField("swap", 1),
        Padding(1),
        BitField("mirror", 1),
        BitField("rot_high", 4),
    ),
    22.5 / 256  # degrees to multiply with
))

FONT = Enum(ULInt8("font"),
        vector = 0,
        off = 1,
        fixed = 2,
#        solid = 3,
#        hatch = 4,
#        off = 5,
#        value = 6,
#        name = 7,
#        both = 8,
#        off = 9,
#        pad = 10,
#        pin = 11,
#        both = 12,
#        point = 13,
#        short = 14,
#        middle = 15,
#        long = 16,
#        sup = 32,
#        64 -> segmentation fault !!!
#        128 -> (null)
)

DRAWING = Struct("DRAWING",
    ULInt16("file_type"),
    ULInt32("record_count"),
    ULInt8("major_version"),
    ULInt8("minor_version"),
    Padding(2),
    Embed(BitStruct("flags_1",
        Padding(5),
        Enum(BitField("alwaysvectorfont", 1),
            no = 0,
            yes = 1,
        ),
        Padding(2),
    )),
    Padding(11),
)

# this one is completely unknown
SETTINGS = Struct("SETTINGS",
    Padding(22),
)

GRID = Struct("GRID",
    Embed(BitStruct("flags_1",
        Padding(6),
        Enum(BitField("style", 1),
            lines = 0,
            dots = 1,
        ),
        Enum(BitField("display", 1),
            no = 0,
            yes = 1,
        ),
        Enum(BitField("altunit", 2),
            mic = 0,
            mm = 1,
            mil = 2,
            inch = 3,
        ),
        Enum(BitField("altunitdist", 2),
            mic = 0,
            mm = 1,
            mil = 2,
            inch = 3,
        ),
        Enum(BitField("unit", 2),
            mic = 0,
            mm = 1,
            mil = 2,
            inch = 3,
        ),
        Enum(BitField("unitdist", 2),
            mic = 0,
            mm = 1,
            mil = 2,
            inch = 3,
        ),
    )),
    SLInt32("multiple"),
    LFloat64("distance"),
    LFloat64("altdistance"),
)

LAYER = Struct("LAYER",
    Peek(ULInt8("visibility_flags")),
    Embed(BitStruct("visibility_flags",
        Padding(3),
        BitField("linked", 1),
        Padding(1),
        BitField("visible", 1),
        BitField("active", 1),
        Padding(1),
    )),
    ULInt8("number"),
    ULInt8("dual"),
    ULInt8("fill"),
    ULInt8("color"),
    Padding(8),
    EagleText("name", 9),
)

SCHEMATIC = Struct("SCHEMATIC",
    Padding(10),
    ULInt32("attribute_count"),
    Padding(3, pattern = "\x00", strict=True),
    EagleText("xrefinfo", 5),
)

LIBRARY = Struct("LIBRARY",
    Padding(2, pattern = "\x00", strict=True),
    ULInt32("device_set_rec_count"),
    ULInt32("symbol_rec_count"),
    ULInt32("package_rec_count"),
    EagleText("name", 8),
)

DEVICE_SETS = Struct("DEVICE_SETS",
    ULInt16("unknown_1"),
    ULInt32("record_count"),
    ULInt32("deviceset_count"),
    ULInt32("unknown_2"),
    EagleText("library", 8),
)

SYMBOLS = Struct("SYMBOLS",
    Padding(2),
    ULInt32("record_count"),
    ULInt32("symbol_count"),
    ULInt32("unknown_2"),
    EagleText("library", 8),
)

PACKAGES = Struct("PACKAGES",
    Padding(2),
    ULInt32("record_count"),
    ULInt32("package_count"),
    Padding(4),
    EagleText("library", 8),
)

SHEET = Struct("SHEET",
    ULInt16("rec_count"),
    Padding(8),
    ULInt32("part_rec_count"),
    ULInt32("bus_rec_count"),
    ULInt32("net_rec_count"),
)

SYMBOL = Struct("SYMBOL",
    ULInt16("rec_count"),
    Padding(5),
    ULInt8("library_id"),
    Padding(6),
    EagleText("name", 8),
)

PACKAGE = Struct("PACKAGE",
    ULInt16("rec_count"),
    Padding(9),
    EagleText("description", 5),
    EagleText("name", 6),
)

NET = Struct("NET",
    ULInt16("rec_count"),
    Const(ULInt32("const1"), 0x7fff7fff),
    Const(ULInt32("const2"), 0x80008000),
    Padding(1),
    ULInt16("net_class"),
    Padding(1),
    EagleText("name", 8),
)

SEGMENT = Struct("SEGMENT",
    ULInt16("rec_count"),
    Padding(20),
)

POLYGON = Struct("POLYGON",
    ULInt16("vertex_count"),
    Padding(8), # could be a bounding box, dimensions ?
    EagleFloat(SLInt16("width"), 5000),
    EagleFloat(ULInt16("spacing"), 5000),
    Padding(2),
    ULInt8("layer"),
    Padding(5),
)

WIRE = WireCurve(Struct("WIRE",
    Padding(1),
    ULInt8("layer"),
    SLInt32("x1"),
    SLInt32("y1"),
    SLInt32("x2"),
    SLInt32("y2"),
    EagleFloat(SLInt16("width"), 5000),
    Embed(BitStruct("flags1",
        Padding(2),
        BitField("curvesign", 1),
        Enum(BitField("cap", 1),
            default0 = 0,
            flat = 1,
        ),
        Enum(BitField("style", 4),
            plain = 0,
            longdash = 1,
            shortdash = 2,
            dashdot = 3,
#            flat = 4,
#            round = 5,
#            vector = 6,
#            proportional = 7,
#            fixed = 8,
        ),
        BitField("common", 1),
        BitField("complex", 4),
        BitField("curve90", 1),
        Padding(2),
    )),
))

CIRCLE = Struct("CIRCLE",
    Padding(1),
    ULInt8("layer"),
    EagleFloat(SLInt32("x")),
    EagleFloat(SLInt32("y")),
    EagleFloat(SLInt32("radius")),
    EagleFloat(SLInt32("radius1")), # same value as radius field
    EagleFloat(SLInt16("width"), 5000),
    Padding(2),
)

RECTANGLE = Struct("RECTANGLE",
    Padding(1),
    ULInt8("layer"),
    EagleFloat(SLInt32("x1")),
    EagleFloat(SLInt32("y1")),
    EagleFloat(SLInt32("x2")),
    EagleFloat(SLInt32("y2")),
    ROTATION,
    Padding(2),
)

JUNCTION = Struct("JUNCTION",
    Padding(1),
    ULInt8("layer"),
    EagleFloat(SLInt32("x")),
    EagleFloat(SLInt32("y")),
    Const(ULInt32("const1"), 0x000013d8),
    Padding(8),
)

HOLE = Struct("HOLE",
    Padding(2),
    EagleFloat(SLInt32("x")),
    EagleFloat(SLInt32("y")),
    EagleFloat(ULInt16("drill"), 5000),
    Padding(10),
)

PAD = Struct("PAD",
    Enum(ULInt8("shape"),
        square = 0,
        round = 1,
        octagon = 2,
        long = 3,
        offset = 4,
        _default_ = Pass
    ),
    Padding(1),
    EagleFloat(SLInt32("x")),
    EagleFloat(SLInt32("y")),
    EagleFloat(ULInt16("drill"), 5000),
    EagleFloat(ULInt16("diameter"), 5000),
    ROTATION,
    Embed(BitStruct("flags",
        Padding(4),
        Enum(BitField("first", 1),
            yes = 1,
            no = 0,
        ),
        Enum(BitField("thermals", 1),
            yes = 0,
            no = 1,
        ),
        Enum(BitField("cream", 1),
            yes = 0,
            no = 1,
        ),
        Enum(BitField("stop", 1),
            yes = 0,
            no = 1,
        ),
    )),
    EagleText("name", 5),
)

SMD = Struct("SMD",
    SLInt8("roundness"),
    ULInt8("layer"),
    EagleFloat(SLInt32("x")),
    EagleFloat(SLInt32("y")),
    EagleFloat(ULInt16("dx"), 5000),
    EagleFloat(ULInt16("dy"), 5000),
    ROTATION,
    Embed(BitStruct("flags",
        Padding(5),
        Enum(BitField("thermals", 1),
            yes = 0,
            no = 1,
        ),
        Enum(BitField("cream", 1),
            yes = 0,
            no = 1,
        ),
        Enum(BitField("stop", 1),
            yes = 0,
            no = 1,
        ),
    )),
    EagleText("name", 5),
)

PIN = Struct("PIN",
    Embed(BitStruct("flags",
        Enum(BitField("visible", 2),
            off = 0,
            pad = 1,
            pin = 2,
            on = 3,
        ),
        Padding(2),
        Enum(BitField("function", 4),
            none = 0,
            dot = 1,
            clk = 2,
            dotclk = 3,
            _default_ = Pass,
        ),
    )),
    Padding(1),
    EagleFloat(SLInt32("x")),
    EagleFloat(SLInt32("y")),
    Embed(
        RotationAdapter(
            BitStruct("flags",
                BitField("rotation", 2),
                Enum(BitField("length", 2),
                    point = 0,
                    short = 1,
                    middle = 2,
                    long = 3,
                ),
                Enum(BitField("direction", 4),
                    NC = 0,
                    IN = 1,
                    OUT = 2,
                    NONE = 3,
                    OC = 4,
                    PWR = 5,
                    PAS = 6,
                    HIZ = 7,
                    SUP = 8,
                    _default_ = Pass
                ),
            ),
            90  # rotation adapter: degrees to multiply with
        )
    ),
    ULInt8("swaplevel"),
    EagleText("name", 10),
)

GATE = Struct("GATE",
    Padding(2),
    EagleFloat(SLInt32("x")),
    EagleFloat(SLInt32("y")),
    Embed(BitStruct("flags",
        Padding(5),
        Enum(BitField("addlevel", 3),
            must = 0,
            none = 2,
            request = 3,
            always = 4,
            _default_ = Pass
        ),
    )),
    ULInt8("swaplevel"),
    ULInt16("symbol"),
    EagleText("name", 8),
)

INSTANCE = Struct("INSTANCE",
    ULInt16("attr_count"),
    EagleFloat(SLInt32("x")),
    EagleFloat(SLInt32("y")),
    Padding(2),
    ULInt16("gate"),
    ROTATION,
    Embed(BitStruct("flags",
        Padding(7),
        Enum(BitField("smashed", 1),
            yes = 1,
            no = 0,
        ),
    )),
    Padding(5),
)

TEXT = SizeAdapter(Struct("TEXT",
    FONT,
    ULInt8("layer"),
    EagleFloat(SLInt32("x")),
    EagleFloat(SLInt32("y")),
    ULInt16("size_low"),
    Embed(BitStruct("flags",
        Padding(1),
        BitField("ratio", 5),
        BitField("size_high", 2),
    )),
    Padding(1),
    ROTATION,
    EagleText("text", 6),
))

LABEL = SizeAdapter(Struct("LABEL",
    FONT,
    ULInt8("layer"),
    EagleFloat(SLInt32("x")),
    EagleFloat(SLInt32("y")),
    ULInt16("size_low"),
    Embed(BitStruct("flags",
        Padding(1),
        BitField("ratio", 5),
        BitField("size_high", 2),
    )),
    Padding(1),
    ROTATION,
    Embed(BitStruct("flags",
        Padding(7),
        BitField("xref", 1),
    )),
    Padding(5),
))

NAME_ATTR = Struct("NAME",
    FONT,
    ULInt8("layer"),
    EagleFloat(SLInt32("x")),
    EagleFloat(SLInt32("y")),
    EagleFloat(SLInt16("size"), 5000),
    Embed(BitStruct("flags",
        Padding(2),
        BitField("ratio", 4),
        Padding(2),
    )),
    Padding(1),
    ROTATION,
    Padding(6),
)

VALUE_ATTR = Struct("VALUE",
    FONT,
    ULInt8("layer"),
    EagleFloat(SLInt32("x")),
    EagleFloat(SLInt32("y")),
    EagleFloat(SLInt16("size"), 5000),
    Embed(BitStruct("flags",
        Padding(2),
        BitField("ratio", 4),
        Padding(2),
    )),
    Padding(1),
    ROTATION,
    Padding(6),
)

DEVICE = Struct("DEVICE",
    ULInt16("connects_count"),
    ULInt16("package"),
    EagleText("techstr", 13),
    EagleText("name", 5),
)

DEVICE_SET = Struct("DEVICE_SET",
    ULInt16("gate_count"), # not sure about this
    ULInt16("record_count"),
    Embed(BitStruct("flags",
        Padding(7),
        Enum(BitField("uservalue", 1),
            no = 0,
            yes = 1,
        ),
    )),
    Padding(1),
    EagleText("prefix", 5),
    EagleText("description", 5),
    EagleText("name", 6),
)

PART = Struct("PART",
    ULInt16("instance_count"),
    ULInt16("library"),
    ULInt16("deviceset"),
    ULInt8("device"),
    ULInt16("technology"),
    EagleText("name", 5),
    EagleText("value", 8),
)

BUS = Struct("BUS",
    ULInt16("record_count"),
    EagleText("name", 20),
)

CONNECTS = Struct("CONNECTS",
    Array(22, ULInt8("connects"))
)

PIN_REF = Struct("PIN_REF",
    Padding(2),
    ULInt16("part"),
    ULInt16("gate"),
    ULInt16("pin"),
    Padding(14),
)

PART_ATTR = Struct("PART",
    FONT,
    ULInt8("layer"),
    EagleFloat(SLInt32("x")),
    EagleFloat(SLInt32("y")),
    EagleFloat(SLInt16("size"), 5000),
    Embed(BitStruct("flags",
        Padding(2),
        BitField("ratio", 4),
        Padding(2),
    )),
    Padding(1),
    ROTATION,
    Padding(6),
)

ATTRIBUTE = Struct("ATTRIBUTE",
    Padding(1),
    ULInt8("layer"),
    EagleFloat(SLInt32("x")),
    EagleFloat(SLInt32("y")),
    EagleFloat(SLInt16("size"), 5000),
    Embed(BitStruct("flags",
        Padding(2),
        BitField("ratio", 4),
        Padding(2),
    )),
    Padding(1),
    ROTATION,
    EagleText("name", 6),
)

ATTRIBUTE_DEF = Struct("ATTRIBUTE_DEF",
    Padding(5),
    EagleText("attribute_def", 16),
    Padding(1),
)

FRAME = Struct("FRAME",
    Padding(1),
    ULInt8("layer"),
    EagleFloat(SLInt32("x1")),
    EagleFloat(SLInt32("y1")),
    EagleFloat(SLInt32("x2")),
    EagleFloat(SLInt32("y2")),
    ULInt8("columns"),
    ULInt8("rows"),
    Embed(BitStruct("flags",
        Padding(4),
        BitField("bleft", 1),
        BitField("btop", 1),
        BitField("bright", 1),
        BitField("bbottom", 1),
    )),
    Padding(1),
)

